# Generated by Django 2.0.2 on 2018-02-13 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cust_data', '0002_person_dob'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cust_data.Person'),
        ),
    ]
