# Generated by Django 2.0.2 on 2018-02-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
