# Generated by Django 2.0.2 on 2018-02-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNum', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('surName', models.CharField(max_length=100)),
                ('postal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_addr', to='cust_data.Address')),
                ('residential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='res_addr', to='cust_data.Address')),
            ],
        ),
    ]
