# Generated by Django 2.0.2 on 2018-02-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust_data', '0003_account_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
