# Generated by Django 2.0.2 on 2018-02-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_data', '0005_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='houseNum',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='DOB',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='surName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='postal',
            new_name='postal_address',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='residential',
            new_name='residential_address',
        ),
    ]
